# Generated by Django 5.0.1 on 2024-01-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='files/')),
                ('to', models.CharField(choices=[('to_Latin', 'to_Latin'), ('to_Cyrillic', 'to_Cyrillic')], max_length=12)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConvertTextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('to', models.CharField(choices=[('to_Latin', 'to_Latin'), ('to_Cyrillic', 'to_Cyrillic')], max_length=12)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
